package com.kodepad.irc

object TestConstants {
    const val HANDLER_EXECUTION_TIMEOUT_IN_MILLIS = 200L
    const val DESERIALIZATION_TIMEOUT_IN_MILIS = 300L
    const val SERIALIZATION_TIMEOUT_IN_MILIS = 100L
    const val INTEGRATION_TEST_TIMEOUT_IN_MILIS = 30_000L
}