package com.kodepad.irc.handler

import com.kodepad.irc.NetworkState
import com.kodepad.irc.connection.Connection
import com.kodepad.irc.event.EventDispatcher

class CommandHandlerFactory(
    private val connection: Connection,
    private val networkState: NetworkState,
    private val eventDispatcher: EventDispatcher,
) {
    fun getHandler(command: Command): Handler {
        return when(command) {
            Command.COMMAND_PING -> PingHandler(connection, networkState)
            Command.COMMAND_NOTICE -> NoticeHandler(eventDispatcher)
            Command.COMMAND_MODE -> ModeHandler()
            Command.COMMAND_PRIVMSG -> PrivMsgHandler(eventDispatcher)
            Command.COMMAND_JOIN -> JoinHandler()
            Command.COMMAND_001 -> RplWelcomeHandler()
            Command.COMMAND_002 -> RplYourHostHandler()
            Command.COMMAND_003 -> RplCreatedHandler()
            Command.COMMAND_004 -> RplMyinfoHandler()
            Command.COMMAND_005 -> RplISupportHandler()
            Command.COMMAND_010 -> RplBounceHandler()
            Command.COMMAND_221 -> RplUModeIsHandler()
            Command.COMMAND_250 -> RplStatsConnHandler()
            Command.COMMAND_251 -> RplLUserClientHandler()
            Command.COMMAND_252 -> RplLUserOpHandler()
            Command.COMMAND_253 -> RplLUserUnknownHandler()
            Command.COMMAND_254 -> RplLUserChannelsHandler()
            Command.COMMAND_255 -> RplLUserMeHandler()
            Command.COMMAND_256 -> RplAdminMeHandler()
            Command.COMMAND_257 -> RplAdminLoc1Handler()
            Command.COMMAND_258 -> RplAdminLoc2Handler()
            Command.COMMAND_259 -> RplAdminEmailHandler()
            Command.COMMAND_263 -> RplTryAgainHandler()
            Command.COMMAND_265 -> RplLocalUsersHandler()
            Command.COMMAND_266 -> RplGlobalUsersHandler()
            Command.COMMAND_276 -> RplWhoIsCertFpHandler()
            Command.COMMAND_300 -> RplNoneHandler()
            Command.COMMAND_301 -> RplAwayHandler()
            Command.COMMAND_302 -> RplUserHostHandler()
            Command.COMMAND_303 -> RplIsOnHandler()
            Command.COMMAND_305 -> RplUnAwayHandler()
            Command.COMMAND_306 -> RplNowAwayHandler()
            Command.COMMAND_311 -> RplWhoIsUserHandler()
            Command.COMMAND_312 -> RplWhoIsServerHandler()
            Command.COMMAND_313 -> RplWhoIsOperatorHandler()
            Command.COMMAND_314 -> RplWhoWasUserHandler()
            Command.COMMAND_317 -> RplWhoIsIdleHandler()
            Command.COMMAND_318 -> RplEndOfWhoIsHandler()
            Command.COMMAND_319 -> RplWhoIsChannelsHandler()
            Command.COMMAND_321 -> RplListStartHandler()
            Command.COMMAND_322 -> RplListHandler()
            Command.COMMAND_323 -> RplListEndHandler()
            Command.COMMAND_324 -> RplChannelModeIsHandler()
            Command.COMMAND_329 -> RplCreationTimeHandler()
            Command.COMMAND_331 -> RplNoTopicHandler()
            Command.COMMAND_332 -> RplTopicHandler()
            Command.COMMAND_333 -> RplTopicWhoTimeHandler()
            Command.COMMAND_341 -> RplInvitingHandler()
            Command.COMMAND_346 -> RplInviteListHandler()
            Command.COMMAND_347 -> RplEndOfInviteListHandler()
            Command.COMMAND_348 -> RplExceptListHandler()
            Command.COMMAND_349 -> RplEndOfExceptListHandler()
            Command.COMMAND_351 -> RplVersionHandler()
            Command.COMMAND_353 -> RplNamReplyHandler()
            Command.COMMAND_366 -> RplEndOfNamesHandler()
            Command.COMMAND_367 -> RplBanListHandler()
            Command.COMMAND_368 -> RplEndOfBanListHandler()
            Command.COMMAND_369 -> RplEndOfWhoWasHandler()
            Command.COMMAND_372 -> RplMotdHandler()
            Command.COMMAND_375 -> RplMotdStartHandler()
            Command.COMMAND_376 -> RplEndOfMotdHandler()
            Command.COMMAND_381 -> RplYouReOperHandler()
            Command.COMMAND_382 -> RplReHashingHandler()
            Command.COMMAND_400 -> ErrUnknownErrorHandler()
            Command.COMMAND_401 -> ErrNoSuchNickHandler()
            Command.COMMAND_402 -> ErrNoSuchServerHandler()
            Command.COMMAND_403 -> ErrNoSuchChannelHandler()
            Command.COMMAND_404 -> ErrCannotSendToChanHandler()
            Command.COMMAND_405 -> ErrTooManyChannelsHandler()
            Command.COMMAND_421 -> ErrUnknownCommandHandler()
            Command.COMMAND_422 -> ErrNoMotdHandler()
            Command.COMMAND_432 -> ErrErroneusNicknameHandler()
            Command.COMMAND_433 -> ErrNicknameInUseHandler()
            Command.COMMAND_441 -> ErrUserNotInChannelHandler()
            Command.COMMAND_442 -> ErrNotOnChannelHandler()
            Command.COMMAND_443 -> ErrUserOnChannelHandler()
            Command.COMMAND_451 -> ErrNotRegisteredHandler()
            Command.COMMAND_461 -> ErrNeedMoreParamsHandler()
            Command.COMMAND_462 -> ErrAlreadyRegisteredHandler()
            Command.COMMAND_464 -> ErrPasswdMismatchHandler()
            Command.COMMAND_465 -> ErrYouReBannedCreepHandler()
            Command.COMMAND_471 -> ErrChannelIsFullHandler()
            Command.COMMAND_472 -> ErrUnknownModeHandler()
            Command.COMMAND_473 -> ErrInviteOnlyChanHandler()
            Command.COMMAND_474 -> ErrBannedFromChanHandler()
            Command.COMMAND_475 -> ErrBadChannelKeyHandler()
            Command.COMMAND_481 -> ErrNoPrivilegesHandler()
            Command.COMMAND_482 -> ErrChanOprIvsNeededHandler()
            Command.COMMAND_483 -> ErrCantKillServerHandler()
            Command.COMMAND_491 -> ErrNoOperHostHandler()
            Command.COMMAND_501 -> ErrUModeUnknownFlagHandler()
            Command.COMMAND_502 -> ErrUsersDontMatchHandler()
            Command.COMMAND_670 -> RplStartTlsHandler()
            Command.COMMAND_691 -> ErrStartTlsHandler()
            Command.COMMAND_723 -> ErrNoPrivsHandler()
            Command.COMMAND_900 -> RplLoggedInHandler()
            Command.COMMAND_901 -> RplLoggedOutHandler()
            Command.COMMAND_902 -> ErrNickLockedHandler()
            Command.COMMAND_903 -> RplSaslSuccessHandler()
            Command.COMMAND_904 -> ErrSaslFailHandler()
            Command.COMMAND_905 -> ErrSaslTooLongHandler()
            Command.COMMAND_906 -> ErrSaslAbortedHandler()
            Command.COMMAND_907 -> ErrSaslAlreadyHandler()
            Command.COMMAND_908 -> RplSaslMechsHandler()
        }
    }
}